#!/bin/bash
function sship(){
#LIMITSSH
mulog=$(cekssh)
data=( `ls /etc/kyt/limit/ssh/ip`);
#Decrypted By YADDY D PHREAKER
    for user in "${data[@]}"
do
iplimit=$(cat /etc/kyt/limit/ssh/ip/$user)
cekcek=$(echo -e "$mulog" | grep $user | wc -l);
if [[ $cekcek -gt $iplimit ]]; then
rm -rf /etc/kyt/limit/ssh/ip/$user
nais=3
echo -e "$waktu\nRemoved User: $user Login: $cekcek IP Max: $ip IP \n" >> /etc/kyt/log/ssh/ssh.log
else
echo > /dev/null
fi
sleep 30
done
if [[ $nais -gt 1 ]]; then
send_log
else
 echo ""
        fi
        sleep 0.1
    done
}
function vmip(){
#LIMITVMESSIP
echo -n > /var/log/xray/access.log
sleep 440
data=( `ls /etc/kyt/limit/vmess/ip`);
#Decrypted By YADDY D PHREAKER
    for user in "${data[@]}"
    do
        iplimit=$(cat /etc/kyt/limit/vmess/ip/$user)
        ehh=$(cat /var/log/xray/access.log | grep "$user" | cut -d " " -f 3 | sed 's/tcp://g' | cut -d ":" -f 1 | sort | uniq);
        cekcek=$(echo -e "$ehh" | wc -l);
        if [[ $cekcek -gt $iplimit ]]; then
            exp=$(grep -w "^### $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
                  sed -i "/^### $user $exp/,/^},{/d" /etc/xray/config.json
                  sed -i "/^### $user $exp/d" /etc/vmess/.vmess.db
                  systemctl restart xray >> /dev/null 2>&1
                  jum2=$(cat /tmp/ipvmess.txt | wc -l)
                  rm -rf /etc/kyt/limit/vmess/ip/$user
                  send_log
                else
            echo ""
        fi
        sleep 0.1
    done
}
function vlip(){
#LIMITVLESSIP
echo -n > /var/log/xray/access.log
sleep 440
data=( `ls /etc/kyt/limit/vless/ip`);
#Decrypted By YADDY D PHREAKER
    for user in "${data[@]}"
    do
        iplimit=$(cat /etc/kyt/limit/vless/ip/$user)
        ehh=$(cat /var/log/xray/access.log | grep "$user" | cut -d " " -f 3 | sed 's/tcp://g' | cut -d ":" -f 1 | sort | uniq);
        cekcek=$(echo -e "$ehh" | wc -l);
        if [[ $cekcek -gt $iplimit ]]; then
            exp=$(grep -w "^#& $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
                  sed -i "/^#& $user $exp/,/^},{/d" /etc/xray/config.json
                  sed -i "/^### $user $exp/d" /etc/vless/.vless.db
                  systemctl restart xray >> /dev/null 2>&1
                  jum2=$(cat /tmp/ipvless.txt | wc -l)
                  rm -rf /etc/kyt/limit/vless/ip/$user
                  send_log
                else
            echo ""
        fi
        sleep 0.1
    done
}
function trip(){
#LIMITIPTROJAN
echo -n > /var/log/xray/access.log
sleep 440
data=( `ls /etc/kyt/limit/trojan/ip`);
#Decrypted By YADDY D PHREAKER
    for user in "${data[@]}"
    do
        iplimit=$(cat /etc/kyt/limit/trojan/ip/$user)
        ehh=$(cat /var/log/xray/access.log | grep "$user" | cut -d " " -f 3 | sed 's/tcp://g' | cut -d ":" -f 1 | sort | uniq);
        cekcek=$(echo -e "$ehh" | wc -l);
        if [[ $cekcek -gt $iplimit ]]; then
            exp=$(grep -w "^#! $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
                  sed -i "/^#! $user $exp/,/^},{/d" /etc/xray/config.json
                  sed -i "/^### $user $exp/d" /etc/trojan/.trojan.db
                  systemctl restart xray >> /dev/null 2>&1
                  jum2=$(cat /tmp/iptrojan.txt | wc -l)
                  rm -rf /etc/kyt/limit/trojan/ip/$user
                  send_log
                else
            echo ""
        fi
        sleep 0.1
    done
}

if [[ ${1} == "sship" ]]; then
ssh
if [[ ${1} == "vmip" ]]; then
vmip
elif [[ ${1} == "vlip" ]]; then
vlip
elif [[ ${1} == "trip" ]]; then
trip
fi




