#!/bin/bash

function send_log() {
    # Fungsi untuk mengirim log ke Telegram
    # Sesuaikan dengan konfigurasi bot Telegram Anda
    CHATID="ID_CHAT_ANDA"
    KEY="TOKEN_BOT_ANDA"
    TIME="10"
    URL="https://api.telegram.org/bot$KEY/sendMessage"
    TEXT="
<code>────────────────────</code>
<b>⚠️ NOTIFIKASI MULTI LOGIN ⚠️</b>
<code>────────────────────</code>
<code>Username  : </code><code>$user</code>
<code>Limit Ip    : </code><code>${iplimit}</code>
<code>Login Ip    : </code><code>${cekcek}</code>
<code>────────────────────</code>
"
    curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

function lock_account() {
    # Fungsi untuk mengunci akun
    local user=$1
    local exp=$2

    sed -i "/^$exp $user/,/^},{/d" /etc/xray/config.json
    sed -i "/^$user $exp/d" /etc/vmess/.vmess.db
    systemctl restart xray >> /dev/null 2>&1
    rm -rf /etc/kyt/limit/vmess/ip/$user
    send_log
}

function unlock_account() {
    # Fungsi untuk membuka kunci akun setelah 15 menit
    local user=$1
    local exp=$2

    sed -i "/^$exp $user/,/^},{/d" /etc/xray/config.json
    sed -i "/^$user $exp/d" /etc/vmess/.vmess.db
    systemctl restart xray >> /dev/null 2>&1
    rm -rf /etc/kyt/limit/vmess/ip/$user
    send_log
}

function vmip() {
    # Fungsi untuk mengunci akun VMess berdasarkan batasan IP
    data=( $(ls /etc/kyt/limit/vmess/ip) )
    for user in "${data[@]}"
    do
        iplimit=$(cat /etc/kyt/limit/vmess/ip/$user)
        ehh=$(cat /var/log/xray/access.log | grep "$user" | cut -d " " -f 3 | sed 's/tcp://g' | cut -d ":" -f 1 | sort | uniq)
        cekcek=$(echo -e "$ehh" | wc -l)
        exp=$(grep -w "^### $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)

        if [[ $cekcek -gt $iplimit ]]; then
            lock_account $user $exp
            echo "$(date +%s)" > /etc/kyt/limit/vmess/locktime/$user
        elif [[ -f "/etc/kyt/limit/vmess/locktime/$user" ]]; then
            local locktime=$(cat "/etc/kyt/limit/vmess/locktime/$user")
            local currenttime=$(date +%s)
            local elapsedtime=$((currenttime - locktime))
            local unlocktime=$((15 * 60))  # 15 menit dalam detik

            if [[ $elapsedtime -ge $unlocktime ]]; then
                unlock_account $user $exp
                rm -f "/etc/kyt/limit/vmess/locktime/$user"
            fi
        fi

        sleep 0.1
    done
}

# Fungsi-fungsi lainnya tetap sama
# ...

function auto_lock_accounts() {
    vmip
    vlip
    trip
}

auto_lock_accounts
